#!/usr/bin/env bash
# This script displays from 1 to 20 with some bad luck messages

count=1
while [ $count -le 20 ]
do
	echo $count
    case $count in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    ((count++))
done
